export function mediaConnectionPanel() {
  return `<details class="media-connection glass" id="mediaConnection"><summary><span><b>اتصال فضای عکس و فیلم</b><small>فضای مستقل نگاه جوان در ابرآروان</small></span><span id="mediaConnectionBadge">نیاز به اتصال</span></summary><form id="mediaConnectionForm"><p class="helper">اطلاعات فضای ابری موجود را از پنل ابرآروان وارد کنید. نام فضا باید با negahjavan شروع شود. کلید دسترسی باید مجوز خواندن و نوشتن همین فضا را داشته باشد.</p><div class="media-settings-grid"><div class="field"><label for="mediaEndpoint">نشانی فضای ابری (Endpoint)</label><input id="mediaEndpoint" type="url" dir="ltr" required placeholder="نشانی HTTPS از پنل ابرآروان"></div><div class="field"><label for="mediaBucket">نام فضای مستقل (Bucket)</label><input id="mediaBucket" dir="ltr" required placeholder="negahjavan-media" pattern="negahjavan[a-z0-9-]*"></div><div class="field"><label for="mediaRegion">منطقه (Region)</label><input id="mediaRegion" dir="ltr" required placeholder="مطابق پنل ابرآروان"></div><div class="field"><label for="mediaAccessKey">کلید دسترسی (Access Key)</label><input id="mediaAccessKey" type="password" dir="ltr" autocomplete="off" required></div><div class="field"><label for="mediaSecretKey">کلید محرمانه (Secret Key)</label><input id="mediaSecretKey" type="password" dir="ltr" autocomplete="new-password" required></div></div><p class="helper">کلیدها رمزگذاری می‌شوند و پس از ذخیره در پنل نمایش داده نمی‌شوند.</p><div class="media-connect-actions"><button id="saveMediaConnection" class="btn btn-primary">بررسی و ذخیره اتصال</button><p id="mediaConnectionMessage" role="status" aria-live="polite"></p></div></form></details>`;
}

function uploadCard(kind, label, formats, accept) {
  return `<section class="media-upload-card" aria-labelledby="${kind}UploadTitle"><div class="media-upload-heading"><h3 id="${kind}UploadTitle">${label}</h3><span>${formats}</span></div><label class="media-file-label" for="${kind}File">انتخاب ${kind==='image'?'عکس':'فیلم'} از دستگاه<input id="${kind}File" class="media-file-input" type="file" accept="${accept}" aria-describedby="${kind}UploadStatus"></label><div id="${kind}FilePreview" class="media-file-preview" hidden></div><progress id="${kind}UploadProgress" max="100" value="0" hidden aria-label="پیشرفت بارگذاری ${label}"></progress><p id="${kind}UploadStatus" class="media-upload-status" role="status" aria-live="polite">فایلی انتخاب نشده است.</p><div class="media-upload-actions"><button id="${kind}Upload" type="button" class="btn btn-primary" disabled>بارگذاری ${kind==='image'?'عکس':'فیلم'}</button><button id="${kind}Clear" type="button" class="btn btn-soft" disabled>حذف از خبر</button></div></section>`;
}
export function mediaComposer() {
  return `<div class="media-section-head"><h3>عکس و فیلم خبر</h3><p id="mediaAvailability" class="helper">برای بارگذاری، فضای ابرآروان را وصل کنید.</p></div><div class="media-upload-grid">${uploadCard('image','تصویر شاخص','تا ۸ مگابایت','image/jpeg,image/png,image/webp,image/gif')}${uploadCard('video','ویدئوی خبر','تا ۵۰ مگابایت','video/mp4,video/webm')}</div><details class="media-manual"><summary>سازگاری پخش ویدیو</summary><p class="helper">برای ویدیوی MP4 بارگذاری‌شده، نسخهٔ سبک‌تر و نسخهٔ WebM را اضافه کنید تا پخش در مرورگرهای بیشتری ممکن شود. اتصال نسخه‌ها مستقیم ذخیره می‌شود.</p><div class="media-upload-grid"><div class="field"><label for="renditionMp4">نسخهٔ سبک MP4</label><input id="renditionMp4" type="file" accept="video/mp4"></div><div class="field"><label for="renditionWebm">نسخهٔ جایگزین WebM</label><input id="renditionWebm" type="file" accept="video/webm"></div></div><button id="saveVideoRenditions" type="button" class="btn btn-primary" disabled>بارگذاری و اتصال نسخه‌ها</button><p id="videoRenditionsStatus" class="media-upload-status" role="status" aria-live="polite">ابتدا خبر دارای ویدیو را برای ویرایش انتخاب کنید.</p></details><details class="media-manual"><summary>استفاده از لینک عکس یا فیلم</summary><div class="field"><label for="hero_image">لینک تصویر شاخص (اختیاری)</label><input id="hero_image" name="hero_image" type="text" inputmode="url" dir="ltr" maxlength="2048" placeholder="https://..."><p class="helper">بدون عکس، کاور گرافیکی تحریریه نمایش داده می‌شود.</p></div><div class="field"><label for="video_url">لینک مستقیم فیلم (اختیاری)</label><input id="video_url" name="video_url" type="text" inputmode="url" dir="ltr" maxlength="2048" placeholder="https://.../video.mp4"></div><div class="field"><label for="video_type">فرمت فیلم</label><select id="video_type" name="video_type"><option value="video/mp4">MP4</option><option value="video/webm">WebM</option></select></div></details><div class="field"><label for="video_caption">توضیح زیر فیلم (اختیاری)</label><input id="video_caption" name="video_caption" maxlength="240" placeholder="توضیح کوتاه درباره ویدئوی خبر"></div>`;
}

export const mediaEditorStyles = `
.media-section-head .helper,.media-connection .helper{font-size:13px;line-height:1.9}.media-file-label{position:relative!important;display:block!important;padding:13px!important;background:white;border:1px dashed #9dbfb3;border-radius:9px;text-align:center;color:#276e60;cursor:pointer;overflow:hidden;margin:0!important}.media-file-label:focus-within{outline:3px solid #159e9c;outline-offset:3px}.media-file-label .media-file-input{position:absolute;inset:0;opacity:0;cursor:pointer;width:100%;height:100%;padding:0!important;font-size:16px!important}
.media-connection{margin:20px 0;border:1px solid #dce7e6;border-radius:22px;overflow:hidden}.media-connection>summary{cursor:pointer;list-style:none;display:flex;align-items:center;justify-content:space-between;gap:16px;padding:23px 28px}.media-connection>summary::-webkit-details-marker{display:none}.media-connection summary b{display:block;font-size:19px;color:#163b3f}.media-connection summary small{display:block;color:#6d8588;margin-top:5px}.media-connection summary>span:last-child{font-size:12px;padding:8px 12px;border-radius:30px;background:#fff2e7;color:#8e552d;white-space:nowrap}.media-connection.is-connected summary>span:last-child{background:#e3f4ec;color:#267754}.media-connection>form{padding:0 28px 27px;border-top:1px solid #dce7e6}.media-settings-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 24px}.media-settings-grid input{min-width:0;width:100%}.media-connect-actions{display:flex;gap:15px;align-items:center;flex-wrap:wrap}.media-connect-actions p{font-size:13px;margin:0;color:#2b785e;overflow-wrap:anywhere}.media-connect-actions p.is-error{color:#b72d4b}.media-section-head h3{font-size:20px;margin:0 0 5px}.media-upload-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;margin:18px 0}.media-upload-card{min-width:0;padding:18px;border:1px solid #d5e4e2;background:#f7fbfa;border-radius:18px}.media-upload-heading{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:14px}.media-upload-heading h3{font-size:17px;margin:0;color:#173b40}.media-upload-heading span{font-size:11px;color:#6a8586}.media-file-label{display:block;font-size:13px;margin-bottom:8px}.media-file-input{display:block;max-width:100%;width:100%;padding:8px!important;font-size:11px!important;background:white}.media-file-input::file-selector-button{border:0;border-radius:7px;padding:9px;background:#e5f3ee;color:#256a5e;margin-inline-end:8px;cursor:pointer;font-family:inherit}.media-file-preview{margin-top:14px;overflow:hidden;border-radius:11px;background:#e7efed}.media-file-preview img,.media-file-preview video{display:block;width:100%;max-height:270px;object-fit:contain}.media-file-preview img{aspect-ratio:16/9}.media-upload-card progress{width:100%;height:8px;accent-color:#238574;margin-top:14px}.media-upload-status{color:#577174;font-size:12px;line-height:1.8;margin:12px 0;overflow-wrap:anywhere;min-height:22px}.media-upload-status.is-error{color:#b72d4b}.media-upload-actions{display:flex;gap:8px;flex-wrap:wrap}.media-upload-actions .btn{font-size:12px;padding:11px 14px}.media-upload-actions .btn:disabled{opacity:.45;cursor:not-allowed}.media-manual{border-block:1px solid #dce7e6;padding:14px 0}.media-manual summary{cursor:pointer;font-size:13px;color:#267565}.media-connection summary:focus-visible,.media-manual summary:focus-visible{outline:3px solid #159e9c;outline-offset:4px}
@media(max-width:1024px){.media-upload-grid{grid-template-columns:1fr}.media-settings-grid{gap:0 16px}}@media(max-width:600px){.media-connection{border-radius:18px}.media-connection>summary{padding:20px;align-items:flex-start;flex-direction:column;gap:10px}.media-connection>form{padding:0 20px 22px}.media-connection summary b{font-size:17px}.media-connection summary small{font-size:12px}.media-settings-grid{grid-template-columns:1fr}.media-upload-card{padding:16px}.media-upload-actions .btn{font-size:13px}.media-upload-status{font-size:13px}.media-section-head h3{font-size:18px}.media-connect-actions{align-items:flex-start;flex-direction:column}.media-connect-actions .btn{max-width:100%}}
`;

export const mediaEditorScript = String.raw`
let mediaConnection={configured:false};
const pendingMedia={image:{file:null,blob:'',xhr:null,version:0},video:{file:null,blob:'',xhr:null,version:0}};
const mediaField=kind=>$('#'+(kind==='image'?'hero_image':'video_url'));
function clientMediaUrl(value){value=String(value||'').trim();if(/^\/media\/[a-f0-9-]{36}\.(jpg|png|webp|gif|mp4|webm)$/.test(value))return value;try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password?u.href:''}catch{return ''}}
function setMediaMessage(kind,text,error=false){const p=$('#'+kind+'UploadStatus');p.textContent=text;p.classList.toggle('is-error',error)}
function refreshMediaPreview(kind){const state=pendingMedia[kind],url=state.blob||clientMediaUrl(mediaField(kind).value),preview=$('#'+kind+'FilePreview');preview.replaceChildren();preview.hidden=!url;if(url){const element=document.createElement(kind==='image'?'img':'video');element.src=url;if(kind==='image')element.alt='پیش‌نمایش تصویر شاخص خبر';else{element.controls=true;element.playsInline=true;element.preload='metadata'}preview.append(element)}$('#'+kind+'Upload').disabled=!state.file||!!state.xhr||!mediaConnection.configured;$('#'+kind+'Clear').disabled=!url&&!state.file}
function releasePendingMedia(kind){const state=pendingMedia[kind];state.version++;state.xhr?.abort();state.xhr=null;if(state.blob)URL.revokeObjectURL(state.blob);state.blob='';state.file=null;$('#'+kind+'File').value='';$('#'+kind+'UploadProgress').hidden=true}
function resetMediaSelection(){resetVideoRenditions();for(const kind of ['image','video']){releasePendingMedia(kind);refreshMediaPreview(kind);setMediaMessage(kind,mediaField(kind).value?'فایل ذخیره‌شده به این خبر متصل است.':'فایلی انتخاب نشده است.')}}
function hasPendingMedia(){return Object.values(pendingMedia).some(state=>state.file||state.xhr)}
function renderMediaConnection(config={}){mediaConnection=config;$('#mediaConnection').classList.toggle('is-connected',!!config.configured);$('#mediaConnectionBadge').textContent=config.configured?'متصل به ابرآروان':'نیاز به اتصال';$('#mediaAvailability').textContent=config.configured?'فضای ابرآروان متصل است. فایل را انتخاب و بارگذاری کنید.':'انتخاب و پیش‌نمایش فعال است؛ برای ذخیره دائمی، بخش «اتصال فضای عکس و فیلم» را تنظیم کنید.';for(const [id,key] of [['mediaEndpoint','endpoint'],['mediaBucket','bucket'],['mediaRegion','region']])if(config[key])$('#'+id).value=config[key];for(const kind of ['image','video'])refreshMediaPreview(kind);refreshVideoRenditions()}
function fileMime(file){if(file.type)return file.type.toLowerCase();const extension=file.name.split('.').pop().toLowerCase();return ({jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',webp:'image/webp',gif:'image/gif',mp4:'video/mp4',webm:'video/webm'})[extension]||''}
const videoRenditions={mp4:{file:null,url:''},webm:{file:null,url:''},busy:false,xhr:null,version:0};
const renditionInput=format=>$('#rendition'+(format==='mp4'?'Mp4':'Webm'));
function renditionMessage(text,error=false){$('#videoRenditionsStatus').textContent=text;$('#videoRenditionsStatus').classList.toggle('is-error',error)}
function refreshVideoRenditions(){const original=$('#video_url').value,valid=/^\/media\/[a-f0-9-]{36}\.mp4$/.test(original);$('#saveVideoRenditions').disabled=videoRenditions.busy||!mediaConnection.configured||!valid||!['mp4','webm'].some(format=>videoRenditions[format].file||videoRenditions[format].url);for(const format of ['mp4','webm'])renditionInput(format).disabled=videoRenditions.busy}
function resetVideoRenditions(){videoRenditions.version++;videoRenditions.xhr?.abort();videoRenditions.xhr=null;videoRenditions.busy=false;for(const format of ['mp4','webm']){videoRenditions[format]={file:null,url:''};renditionInput(format).value=''}renditionMessage(/^\/media\/[a-f0-9-]{36}\.mp4$/.test($('#video_url').value)?'نسخه‌های سازگار این ویدیو را انتخاب کنید.':'ابتدا خبر دارای ویدیو را برای ویرایش انتخاب کنید.');refreshVideoRenditions()}
for(const format of ['mp4','webm'])renditionInput(format).addEventListener('change',()=>{const file=renditionInput(format).files[0];videoRenditions[format]={file:null,url:''};if(file){if(fileMime(file)!=='video/'+format||!file.size||file.size>50*1024*1024){renditionInput(format).value='';renditionMessage('فایل '+format.toUpperCase()+' با حجم حداکثر ۵۰ مگابایت انتخاب کنید.',true);refreshVideoRenditions();return}videoRenditions[format].file=file;renditionMessage('نسخه‌ها انتخاب شده‌اند؛ برای اتصال، دکمهٔ بارگذاری را بزنید.')}refreshVideoRenditions()});
$('#video_url').addEventListener('input',resetVideoRenditions);
function uploadVideoRendition(file,format){return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();videoRenditions.xhr=xhr;xhr.open('POST','/api/admin/media');xhr.timeout=180000;xhr.setRequestHeader('Content-Type','video/'+format);xhr.setRequestHeader('X-Upload-Size',String(file.size));xhr.setRequestHeader('X-File-Name',encodeURIComponent(file.name));xhr.upload.onprogress=e=>{if(e.lengthComputable)renditionMessage('بارگذاری '+format.toUpperCase()+'؛ '+Math.round(e.loaded/e.total*100).toLocaleString('fa-IR')+'٪')};xhr.onload=()=>{let data;try{data=JSON.parse(xhr.responseText)}catch{reject(new Error('پاسخ بارگذاری معتبر نیست.'));return}if(xhr.status<200||xhr.status>=300){reject(new Error(data.error||'بارگذاری انجام نشد.'));return}if(data.media?.kind!=='video'||data.media.mime!=='video/'+format||!/^\/media\/[a-f0-9-]{36}\.(mp4|webm)$/.test(data.media.url)){reject(new Error('نسخهٔ بارگذاری‌شده معتبر نیست.'));return}resolve(data.media.url)};xhr.onerror=()=>reject(new Error('ارتباط قطع شد؛ دوباره تلاش کنید.'));xhr.ontimeout=()=>reject(new Error('زمان بارگذاری تمام شد؛ دوباره تلاش کنید.'));xhr.onabort=()=>reject(new Error('بارگذاری لغو شد.'));xhr.send(file)})}
$('#saveVideoRenditions').onclick=async()=>{const original=$('#video_url').value,version=videoRenditions.version;if(videoRenditions.busy||!/^\/media\/[a-f0-9-]{36}\.mp4$/.test(original)||!mediaConnection.configured)return;videoRenditions.busy=true;refreshVideoRenditions();try{const input={original};for(const format of ['mp4','webm']){const state=videoRenditions[format];if(state.file&&!state.url)state.url=await uploadVideoRendition(state.file,format);if(version!==videoRenditions.version)return;if(state.url)input[format]=state.url}renditionMessage('در حال اتصال نسخه‌های ویدیو…');const result=await api('/api/admin/media-renditions',{method:'PUT',body:JSON.stringify(input)});if(version!==videoRenditions.version)return;resetVideoRenditions();renditionMessage('نسخه‌های '+result.media.formats.join(' و ')+' متصل شدند؛ پخش سایت به‌روز شد.');refreshMediaPreview('video')}catch(error){if(version===videoRenditions.version)renditionMessage(error.message,true)}finally{if(version===videoRenditions.version){videoRenditions.busy=false;videoRenditions.xhr=null;refreshVideoRenditions()}}};
for(const kind of ['image','video']){
 $('#'+kind+'File').addEventListener('change',()=>{const file=$('#'+kind+'File').files[0];if(!file)return;releasePendingMedia(kind);const mime=fileMime(file),allowed=kind==='image'?['image/jpeg','image/png','image/webp','image/gif']:['video/mp4','video/webm'];if(!allowed.includes(mime)){setMediaMessage(kind,kind==='image'?'عکس JPG، PNG، WebP یا GIF انتخاب کنید.':'فیلم MP4 یا WebM انتخاب کنید.',true);refreshMediaPreview(kind);return}if(!file.size||file.size>(kind==='image'?8:50)*1024*1024){setMediaMessage(kind,kind==='image'?'حداکثر حجم عکس ۸ مگابایت است.':'حداکثر حجم فیلم ۵۰ مگابایت است.',true);refreshMediaPreview(kind);return}pendingMedia[kind].file=file;pendingMedia[kind].blob=URL.createObjectURL(file);setMediaMessage(kind,file.name+' · '+(file.size/1024/1024).toLocaleString('fa-IR',{maximumFractionDigits:1})+' مگابایت؛ هنوز بارگذاری نشده است.');refreshMediaPreview(kind)});
 $('#'+kind+'Clear').onclick=()=>{releasePendingMedia(kind);mediaField(kind).value='';if(kind==='video')$('#video_caption').value='';setMediaMessage(kind,'فایل از این خبر حذف شد.');refreshMediaPreview(kind);updatePreview()};
 mediaField(kind).addEventListener('input',()=>{releasePendingMedia(kind);refreshMediaPreview(kind);setMediaMessage(kind,mediaField(kind).value?'لینک فایل به خبر متصل است.':'فایلی انتخاب نشده است.')});
 $('#'+kind+'Upload').onclick=async()=>{const state=pendingMedia[kind],file=state.file;if(!file||!mediaConnection.configured||state.xhr)return;const version=state.version,xhr=new XMLHttpRequest(),progress=$('#'+kind+'UploadProgress');state.xhr=xhr;progress.value=0;progress.hidden=false;refreshMediaPreview(kind);setMediaMessage(kind,'در حال بارگذاری '+file.name+'…');try{const result=await new Promise((resolve,reject)=>{xhr.open('POST','/api/admin/media');xhr.timeout=180000;xhr.setRequestHeader('Content-Type',fileMime(file));xhr.setRequestHeader('X-Upload-Size',String(file.size));xhr.setRequestHeader('X-File-Name',encodeURIComponent(file.name));xhr.upload.onprogress=event=>{if(event.lengthComputable){progress.value=Math.min(99,Math.round(event.loaded/event.total*100));setMediaMessage(kind,progress.value.toLocaleString('fa-IR')+'٪؛ در حال انتقال فایل…')}};xhr.onload=()=>{let data;try{data=JSON.parse(xhr.responseText)}catch{reject(new Error('پاسخ بارگذاری معتبر نیست.'));return}if(xhr.status<200||xhr.status>=300){reject(new Error(data.error||'بارگذاری انجام نشد.'));return}if(data.media?.kind!==kind||!clientMediaUrl(data.media?.url)){reject(new Error('فایل ذخیره‌شده معتبر نیست.'));return}resolve(data.media)};xhr.onerror=()=>reject(new Error('ارتباط قطع شد؛ دوباره تلاش کنید.'));xhr.ontimeout=()=>reject(new Error('زمان بارگذاری تمام شد؛ دوباره تلاش کنید.'));xhr.onabort=()=>reject(new Error('بارگذاری لغو شد.'));xhr.send(file)});if(version!==state.version)return;mediaField(kind).value=result.url;if(kind==='video')$('#video_type').value=result.mime;releasePendingMedia(kind);progress.value=100;progress.hidden=false;setMediaMessage(kind,'بارگذاری کامل شد؛ با ذخیره خبر منتشر می‌شود.');refreshMediaPreview(kind);updatePreview()}catch(error){if(version!==state.version)return;state.xhr=null;setMediaMessage(kind,error.message,true);refreshMediaPreview(kind)}};
}
$('#mediaConnectionForm').onsubmit=async event=>{event.preventDefault();const button=$('#saveMediaConnection'),message=$('#mediaConnectionMessage');button.disabled=true;message.classList.remove('is-error');message.textContent='در حال بررسی دسترسی صندوقچه…';try{const result=await api('/api/admin/media-settings',{method:'PUT',body:JSON.stringify({endpoint:$('#mediaEndpoint').value,bucket:$('#mediaBucket').value,region:$('#mediaRegion').value,access_key:$('#mediaAccessKey').value,secret_key:$('#mediaSecretKey').value})});renderMediaConnection(result.media);$('#mediaAccessKey').value='';$('#mediaSecretKey').value='';message.textContent='دسترسی صندوقچه تأیید شد؛ حالا یک عکس یا فیلم آزمایشی بارگذاری کنید.'}catch(error){message.textContent=error.message;message.classList.add('is-error')}finally{button.disabled=false}};
`;
