import { CATEGORY_LABELS } from './db.js';

const esc = (v='') => String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmtDate = (v) => {
  if (!v) return '';
  try { return new Intl.DateTimeFormat('fa-IR', { dateStyle:'medium', timeStyle:'short' }).format(new Date(v)); }
  catch { return String(v); }
};
const imgStyle = (url) => url ? `style="background-image:linear-gradient(180deg,rgba(4,10,20,.08),rgba(4,10,20,.78)),url('${esc(url)}')"` : '';

const css = `
:root{--bg:#07101a;--bg2:#0c1623;--card:rgba(255,255,255,.07);--card2:rgba(255,255,255,.11);--line:rgba(255,255,255,.12);--text:#f5f8fc;--muted:#aeb9c7;--accent:#4fd1c5;--accent2:#7dd3fc;--red:#ff5a67;--amber:#f6c85f;--shadow:0 24px 80px rgba(0,0,0,.32)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:radial-gradient(circle at 85% -10%,rgba(79,209,197,.14),transparent 34%),radial-gradient(circle at -10% 30%,rgba(125,211,252,.10),transparent 32%),var(--bg);color:var(--text);font-family:Vazirmatn,Tahoma,Arial,sans-serif;direction:rtl;min-height:100vh}a{color:inherit;text-decoration:none}button,input,textarea,select{font:inherit}.wrap{width:min(1180px,calc(100% - 32px));margin:auto}.glass{background:linear-gradient(145deg,rgba(255,255,255,.10),rgba(255,255,255,.045));border:1px solid var(--line);box-shadow:var(--shadow);backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px)}
.top{position:sticky;top:0;z-index:30;background:rgba(7,16,26,.78);backdrop-filter:blur(18px);border-bottom:1px solid rgba(255,255,255,.08)}.top-inner{height:76px;display:flex;align-items:center;gap:22px}.brand{display:flex;align-items:center;gap:11px;font-weight:900;font-size:24px}.mark{width:42px;height:42px;border-radius:14px;display:grid;place-items:center;background:linear-gradient(135deg,var(--accent),var(--accent2));color:#041117;font-weight:1000;box-shadow:0 10px 30px rgba(79,209,197,.25)}.nav{display:flex;gap:16px;overflow:auto;white-space:nowrap;color:#d6dee8;font-size:14px}.nav a:hover{color:#fff}.grow{flex:1}.editor-link{padding:10px 14px;border-radius:12px;border:1px solid var(--line);background:rgba(255,255,255,.05)}
.ticker{margin-top:18px;border-radius:16px;display:flex;align-items:center;overflow:hidden;min-height:48px}.ticker-label{background:var(--red);padding:14px 18px;font-weight:900;white-space:nowrap}.ticker-track{display:flex;gap:32px;overflow:auto;padding:0 18px;color:#f3f6fa}.ticker-track a{white-space:nowrap}.hero{margin-top:22px;min-height:520px;border-radius:30px;position:relative;overflow:hidden;background:linear-gradient(135deg,#11263b,#0b1826 60%,#0d3238);background-size:cover;background-position:center}.hero:after{content:'';position:absolute;inset:0;background:linear-gradient(90deg,rgba(5,12,20,.10),rgba(5,12,20,.86) 74%)}.hero-content{position:relative;z-index:2;min-height:520px;display:flex;flex-direction:column;justify-content:flex-end;padding:clamp(26px,5vw,58px);max-width:820px;margin-right:auto}.eyebrow{display:inline-flex;align-items:center;gap:9px;width:max-content;padding:8px 12px;border-radius:999px;background:rgba(255,255,255,.10);border:1px solid rgba(255,255,255,.13);font-size:13px}.dot{width:8px;height:8px;border-radius:50%;background:var(--red);box-shadow:0 0 0 6px rgba(255,90,103,.12)}h1{font-size:clamp(36px,6vw,70px);line-height:1.08;margin:18px 0 16px;letter-spacing:-1.2px}.hero p{font-size:clamp(16px,2vw,20px);line-height:1.9;color:#d7e0e9;max-width:720px}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:12px}.btn{border:0;border-radius:13px;padding:12px 18px;cursor:pointer}.btn-primary{background:linear-gradient(135deg,var(--accent),var(--accent2));color:#031018;font-weight:900}.btn-soft{background:rgba(255,255,255,.08);color:#fff;border:1px solid var(--line)}
.section{margin-top:42px}.section-head{display:flex;align-items:end;justify-content:space-between;gap:14px;margin-bottom:16px}.section-title{font-size:27px;font-weight:950}.section-sub{color:var(--muted);font-size:13px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.card{border-radius:20px;overflow:hidden;transition:.2s transform,.2s border-color}.card:hover{transform:translateY(-3px);border-color:rgba(125,211,252,.26)}.thumb{height:190px;background:linear-gradient(135deg,#163149,#0f2733);background-size:cover;background-position:center;position:relative}.thumb:after{content:'';position:absolute;inset:0;background:linear-gradient(180deg,transparent 55%,rgba(4,10,18,.65))}.card-body{padding:18px}.tag{display:inline-flex;padding:6px 10px;border-radius:999px;font-size:12px;color:#c9f9f5;background:rgba(79,209,197,.10);border:1px solid rgba(79,209,197,.18)}.card h3{font-size:19px;line-height:1.65;margin:12px 0 8px}.meta{font-size:12px;color:var(--muted);display:flex;gap:12px;flex-wrap:wrap}.excerpt{color:#bcc7d4;line-height:1.9;font-size:14px}.split{display:grid;grid-template-columns:1.15fr .85fr;gap:18px}.feature-list{display:grid;gap:12px}.mini{padding:16px;border-radius:17px;display:grid;grid-template-columns:100px 1fr;gap:14px;align-items:center}.mini-thumb{height:78px;border-radius:12px;background:linear-gradient(135deg,#163149,#0e202e);background-size:cover;background-position:center}.mini h4{margin:0 0 8px;font-size:15px;line-height:1.6}.empty{padding:34px;border-radius:22px;text-align:center;color:var(--muted)}
.footer{margin-top:58px;padding:36px 0 44px;border-top:1px solid rgba(255,255,255,.08);color:var(--muted)}.footer-row{display:flex;justify-content:space-between;gap:20px;flex-wrap:wrap}.notice{margin-top:18px;padding:14px 16px;border-radius:14px;background:rgba(246,200,95,.08);border:1px solid rgba(246,200,95,.20);color:#f8dfa4;font-size:13px}
.article{margin-top:28px;padding:clamp(24px,5vw,54px);border-radius:28px}.article h1{font-size:clamp(34px,5vw,58px)}.article-cover{height:min(56vw,600px);border-radius:24px;margin:24px 0;background:linear-gradient(135deg,#17324a,#0d2332);background-size:cover;background-position:center}.article-body{font-size:18px;line-height:2.2;color:#e4e9ee;white-space:pre-wrap}.source{margin-top:28px;padding:14px 16px;border-radius:14px;background:rgba(255,255,255,.05)}
.searchbar{display:flex;gap:10px}.searchbar input{min-width:0;flex:1;padding:12px 14px;border-radius:12px;border:1px solid var(--line);background:rgba(255,255,255,.06);color:#fff;outline:none}.searchbar input:focus{border-color:rgba(125,211,252,.45)}
.editor-shell{width:min(1180px,calc(100% - 28px));margin:28px auto}.login{max-width:440px;margin:10vh auto;padding:28px;border-radius:24px}.login h1{font-size:34px;margin-top:0}.field{display:grid;gap:7px;margin:12px 0}.field label{font-size:13px;color:var(--muted)}.field input,.field textarea,.field select{width:100%;border:1px solid var(--line);background:rgba(255,255,255,.06);color:#fff;border-radius:12px;padding:12px 13px;outline:none}.field textarea{min-height:140px;resize:vertical}.field select option{background:#0c1623;color:#fff}.error{color:#ff9da6;font-size:13px;min-height:20px}.dash-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:18px}.dash-head h1{font-size:34px;margin:0}.stats{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin:16px 0}.stat{padding:18px;border-radius:18px}.stat b{display:block;font-size:28px}.stat span{color:var(--muted);font-size:12px}.dash-grid{display:grid;grid-template-columns:380px 1fr;gap:18px}.panel{padding:20px;border-radius:22px}.panel h2{margin-top:0}.article-row{display:grid;grid-template-columns:1fr auto;gap:12px;padding:14px 0;border-bottom:1px solid rgba(255,255,255,.08)}.article-row:last-child{border-bottom:0}.row-actions{display:flex;gap:8px;align-items:center}.tiny{padding:7px 9px;border-radius:9px;border:1px solid var(--line);background:rgba(255,255,255,.05);color:#fff;cursor:pointer}.danger{color:#ffb0b6;border-color:rgba(255,90,103,.22)}.status{font-size:11px;padding:5px 8px;border-radius:999px;background:rgba(255,255,255,.08);color:#cbd5df}.status.breaking{background:rgba(255,90,103,.13);color:#ffadb4}.status.published{background:rgba(79,209,197,.12);color:#b9f2ed}
@media(max-width:900px){.grid{grid-template-columns:1fr 1fr}.split,.dash-grid{grid-template-columns:1fr}.stats{grid-template-columns:repeat(2,1fr)}.hero,.hero-content{min-height:460px}.nav{display:none}}
@media(max-width:620px){.wrap{width:min(100% - 20px,1180px)}.top-inner{height:66px}.brand{font-size:20px}.mark{width:36px;height:36px}.editor-link{font-size:12px;padding:8px 10px}.grid{grid-template-columns:1fr}.hero{border-radius:22px}.hero-content{padding:24px}.ticker{border-radius:13px}.ticker-label{padding:13px}.mini{grid-template-columns:82px 1fr}.mini-thumb{height:68px}.article{border-radius:20px}.stats{grid-template-columns:1fr 1fr}.dash-head{align-items:flex-start}.dash-head h1{font-size:28px}}
`;

function shell(title, body, extraHead='') {
  return `<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#07101a"><title>${esc(title)} | نگاه جوان</title><meta name="description" content="نگاه جوان؛ رسانه خبری برای روایت روشن و دقیق تحولات ایران و جهان"><style>${css}</style>${extraHead}</head><body>${body}</body></html>`;
}

function header() {
  const nav = Object.entries(CATEGORY_LABELS).filter(([k])=>k!=='general').map(([k,v])=>`<a href="/category/${k}">${esc(v)}</a>`).join('');
  return `<header class="top"><div class="wrap top-inner"><a class="brand" href="/"><span class="mark">ن</span><span>نگاه جوان</span></a><nav class="nav">${nav}</nav><span class="grow"></span><a class="editor-link" href="/editorial">تحریریه</a></div></header>`;
}

function footer() {
  return `<footer class="footer"><div class="wrap footer-row"><div><b style="color:#fff">نگاه جوان</b><div style="margin-top:7px">روایت روشنِ خبر برای نسل امروز</div></div><div>خبر، تحلیل و دیدگاه باید از یکدیگر تفکیک شوند.</div></div></footer>`;
}

function card(a) {
  return `<article class="card glass"><a href="/news/${encodeURIComponent(a.slug)}"><div class="thumb" ${imgStyle(a.hero_image)}></div><div class="card-body"><span class="tag">${esc(CATEGORY_LABELS[a.category] || 'خبر')}</span><h3>${esc(a.title)}</h3><div class="meta"><span>${esc(fmtDate(a.published_at))}</span><span>${Number(a.views||0).toLocaleString('fa-IR')} بازدید</span></div>${a.excerpt?`<p class="excerpt">${esc(a.excerpt)}</p>`:''}</div></a></article>`;
}

function mini(a) {
  return `<a class="mini glass" href="/news/${encodeURIComponent(a.slug)}"><div class="mini-thumb" ${imgStyle(a.hero_image)}></div><div><span class="tag">${esc(CATEGORY_LABELS[a.category] || 'خبر')}</span><h4>${esc(a.title)}</h4><div class="meta">${esc(fmtDate(a.published_at))}</div></div></a>`;
}

function section(title, slug, items, subtitle='') {
  return `<section class="section"><div class="section-head"><div><div class="section-title">${esc(title)}</div>${subtitle?`<div class="section-sub">${esc(subtitle)}</div>`:''}</div><a class="section-sub" href="/category/${slug}">مشاهده همه ←</a></div>${items.length?`<div class="grid">${items.slice(0,3).map(card).join('')}</div>`:`<div class="empty glass">هنوز خبری در این بخش منتشر نشده است.</div>`}</section>`;
}

export function homePage(data) {
  const hero = data.hero;
  const heroBg = hero?.hero_image ? imgStyle(hero.hero_image) : '';
  const heroBlock = hero ? `<section class="hero glass" ${heroBg}><div class="hero-content"><span class="eyebrow"><span class="dot"></span>${hero.status==='breaking'?'خبر فوری':'انتخاب سردبیر'}</span><h1>${esc(hero.title)}</h1><p>${esc(hero.excerpt || 'متن کامل خبر و جزئیات بیشتر را در صفحه خبر بخوانید.')}</p><div class="actions"><a class="btn btn-primary" href="/news/${encodeURIComponent(hero.slug)}">مطالعه خبر</a><a class="btn btn-soft" href="#latest">آخرین خبرها</a></div></div></section>` : `<section class="hero glass"><div class="hero-content"><span class="eyebrow"><span class="dot"></span>نسخه جدید نگاه جوان<